function [parameters] = parameter_setup

prompt={'Experiment name'...
    'Correction of channel offset (no=0,auto=1,fixed=2)'...
    'mask criterion: AND (0) / OR (1) / REDonly (2) '...
    'SUM threshold'...
    'initial threshold'...
    'single size threshold? (0/1)'...
    'threshold based on perimeter/area ratio? (0/1)'...
    'lower threshold bac size'...
    'upper threshold bac size'...
    'path to results dir'...
    '# consecutive images'...
    'Display detected bacs (0/1)'...
    };

defans = {'',...
    '1'...
    '2'...
    '0'...
    '20'...
    '0'...
    '0'...
    '10'...
    '100'...
    'C:\'...
    '5'...
    '0'...
    };

info = inputdlg(prompt,'Input Parameters',1,defans);

parameters.exp_name = info{1};
parameters.offsetcorr = str2double(info{2});
parameters.or = str2double(info{3});
parameters.sumthres = str2double(info{4});

parameters.binary_thres = str2double(info{5});
parameters.sizethresboolean = str2double(info{6});
parameters.perithresboolean = str2double(info{7});
parameters.sizethres = str2double(info{8});
parameters.sizethres_upperlimit = str2double(info{9});
parameters.loc4dir = info{10};
parameters.consecutive_images = str2double(info{11});
parameters.display_images = str2double(info{12});

objectives = {'20x NA0.5', '20x NA0.75','40x NA0.95', '60x NA0.95','60x NA1.4'};
[parameters.objective,~] = listdlg('PromptString','Select an objective:',...
                'SelectionMode','single',...
                'ListString',objectives);


end





